project:
  type: website
  output-dir: docs

website:
  title: "CUSTOM HOMEPAGE QUARTO"
  navbar:
    left:
      - href: about.qmd
        text: Page standard
      - url: "https://github.com/mthevenin/test_homepage"
        text: Dépôt github
  sidebar:
    contents: 
      - text: "Modification de la homepage"
      - href: modif_homepage.qmd
format:
  html:
    theme:
      light: [simplex, style.scss]
    css: styles.css
    toc: true



